name: Build and Deploy with Pandoc

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Convert Markdown to HTML
        run: |
          mkdir -p build
          # Copy static assets
          cp -r images build/ || true
          cp styles.css build/ || true
          
          # Generate index.html
          pandoc content/index.md \
            -o build/index.html \
            --template=template.html \
            --variable title="Asociación Autismo y Neurodiversidad Esplugues" \
            --variable lang="es" \
            --variable css="styles.css"
          
          # Generate other pages
          for file in content/*.md; do
            if [ "$file" != "content/index.md" ]; then
              filename=$(basename "$file" .md)
              pandoc "$file" \
                -o "build/${filename}.html" \
                --template=template.html \
                --variable title="$filename | Asociación Autismo y Neurodiversidad Esplugues" \
                --variable lang="es" \
                --variable css="styles.css"
            fi
          done

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # The branch the action should deploy to
          folder: build     # The folder the action should deploy
          clean: true       # Automatically remove deleted files from the deploy branch
